// AssemblyInfoExtra.cs
//
// Auto-generated by ZXVersion.exe

using System.Reflection;

[assembly: AssemblyConfiguration("89bf069")]
[assembly: AssemblyCopyright("Copyright © 2017-2026 Robin Verhagen-Guest")]
[assembly: AssemblyVersion("1.6.0.0")]
[assembly: AssemblyFileVersion("1.6.0.0")]
[assembly: AssemblyInformationalVersion("1.6.0.89bf069")]
